services:
  backend:
    image: abhaygehlot/backend:stable
    container_name: backend
    expose:
      - "8000"

  frontend:
    image: abhaygehlot/frontend:stable
    container_name: frontend
    ports:
      - "80:80"
    depends_on:
      - backend
